<?php

namespace toom1996\http;

use toom1996\base\BootstrapInterface;
use toom1996\base\Component;


class Http extends Component implements BootstrapInterface
{
    /**
     * Extension name.
     * @var string
     */
    public string $name = 'http';

    /**
     * Defined config path.
     * @var string 
     */
    public string $configPath = '';

    /**
     * {@inheritDoc}
     */
    public function init()
    {
        $this->configPath = $this->configPath ?: "@eazy/{$this->name}/config";
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * Returns extension id.
     * @return string
     */
    public function getName(): string
    {
        return $this->name;
    }

    /**
     * Returns extension version.
     * @return string
     */
    public function getVersion(): string
    {
        return '1.0.0';
    }

    /**
     * Returns usage.
     * @return string[]
     */
    public function getUsage(): array
    {
        return [
            '-install' => 'Initialization http server. If you use this extension for the first time, please execute this command first.',
            '-start' => 'Start server.',
            '-start -d ' => 'Start server and used daemonize mode.',
            '-stop' => 'Stop server.',
            '-reload' => 'Reload server.',
        ];
    }

    public function getDescription()
    {
        return 'Swoole http server extension.';
    }

    public function bootstrap(): void
    {
        // TODO: Implement bootstrap() method.
    }
}